name: CI-gradle-build

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@master
    - name: setup jdk
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: adopt
        java-package: jdk
        architecture: x64
        cache: gradle

    - name: gradle build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build --info
